import type { NextConfig } from "next";
import { withSentryConfig } from "@sentry/nextjs";

const nextConfig: NextConfig = {
  turbopack: {
    root: ".",
  },
  env: {
    NEXT_PUBLIC_BUILD_ID:
      process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 8) ?? "dev",
  },
  // The /sw.js route used to be a static file under `public/sw.js`
  // and needed an explicit `Cache-Control` + `Service-Worker-Allowed`
  // header here. It's now generated by `src/app/sw.js/route.ts`
  // (so the build ID can be baked into the file content), and the
  // route returns those headers itself — no rewrite needed here.
};

export default withSentryConfig(nextConfig, {
  org: process.env.SENTRY_ORG,
  project: process.env.SENTRY_PROJECT,
  // Be loud whenever we have an auth token (i.e. we're actually trying to
  // upload source maps — Vercel builds, CI). Stay silent in local dev where
  // there's no token. Previously gated on CI, which would silently swallow
  // upload failures if Vercel ever didn't set CI=1.
  silent: !process.env.SENTRY_AUTH_TOKEN,
  widenClientFileUpload: true,
  tunnelRoute: "/monitoring", // avoid ad-blockers eating Sentry requests
});
