import { NextRequest, NextResponse } from "next/server";
import { jwtVerify } from "jose";
import { cookies } from "next/headers";
import { db } from "@/lib/db";
import { qrLoginTokens } from "@/lib/db/schema";
import { and, eq, isNull } from "drizzle-orm";
import * as Sentry from "@sentry/nextjs";

function getSecret() {
  return new TextEncoder().encode(
    process.env.AUTH_SECRET || "dev-secret-change-me"
  );
}

/**
 * GET /q/<id>
 *
 * Architectural-fix replacement for the older
 * `/api/auth/qr-login?token=<jwt>` route. Looks up the short id in
 * `qr_login_tokens`, validates that it's not consumed and not
 * expired, marks it consumed (single-use), and installs the stored
 * session JWT as the `user-session` cookie before redirecting to the
 * appropriate dashboard.
 *
 * Failure paths all redirect to `/login` so a copy-pasted/expired QR
 * URL never surfaces a stack trace to the user.
 */
export async function GET(
  request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  try {
    return await handleRedeem(request, context);
  } catch (err) {
    Sentry.captureException(err, { tags: { area: "qr-login-redeem" } });
    return NextResponse.redirect(new URL("/login", request.url));
  }
}

async function handleRedeem(
  request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  const { id } = await context.params;
  if (!id) return NextResponse.redirect(new URL("/login", request.url));

  // Read the row + its consumed/expired state in one go. The CHECK
  // happens at app level (not via WHERE) so we can mark consumed
  // atomically below regardless of why we're rejecting.
  const [row] = await db
    .select({
      id: qrLoginTokens.id,
      sessionJwt: qrLoginTokens.sessionJwt,
      expiresAt: qrLoginTokens.expiresAt,
      consumedAt: qrLoginTokens.consumedAt,
    })
    .from(qrLoginTokens)
    .where(eq(qrLoginTokens.id, id))
    .limit(1);

  if (!row) return NextResponse.redirect(new URL("/login", request.url));
  if (row.consumedAt)
    return NextResponse.redirect(new URL("/login", request.url));
  if (row.expiresAt.getTime() <= Date.now())
    return NextResponse.redirect(new URL("/login", request.url));

  // Mark consumed atomically — guards the no-replay invariant even if
  // two scans race on the same id (rare, but possible if someone
  // shares a screenshot fast).
  const consumed = await db
    .update(qrLoginTokens)
    .set({ consumedAt: new Date() })
    .where(
      and(eq(qrLoginTokens.id, id), isNull(qrLoginTokens.consumedAt)),
    )
    .returning({ id: qrLoginTokens.id });
  if (consumed.length === 0) {
    // Lost the race — another request consumed it first.
    return NextResponse.redirect(new URL("/login", request.url));
  }

  // The stored JWT is itself signed + has its own 5-min expiry; verify
  // before installing as a session cookie. A failure here is the
  // "shouldn't happen" path — the token was just generated by our
  // own code and the AUTH_SECRET hasn't changed mid-request — so
  // capture it as a real error rather than a user-flow miss.
  let payload;
  try {
    ({ payload } = await jwtVerify(row.sessionJwt, getSecret()));
  } catch (err) {
    Sentry.captureException(err, {
      tags: { area: "qr-login-redeem" },
      extra: { tokenId: id },
    });
    return NextResponse.redirect(new URL("/login", request.url));
  }

  if (payload.purpose !== "qr-login") {
    return NextResponse.redirect(new URL("/login", request.url));
  }

  // Issue a normal 7-day session token, same shape as login does.
  const { SignJWT } = await import("jose");
  const sessionToken = await new SignJWT({
    userId: payload.userId,
    email: payload.email,
    roles: payload.roles,
  })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime("7d")
    .sign(getSecret());

  const jar = await cookies();
  jar.set("user-session", sessionToken, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    maxAge: 60 * 60 * 24 * 7,
    path: "/",
  });

  const roles = Array.isArray(payload.roles) ? (payload.roles as string[]) : [];
  let target = "/member/dashboard";
  if (roles.includes("pro")) target = "/pro/dashboard";
  else if (roles.includes("admin") || roles.includes("dev")) target = "/admin";

  return NextResponse.redirect(new URL(target, request.url));
}
